### ISSUE TITLE
Relax requirement for application/rdf+json in queryQuads

### ISSUE THREAD

**Issue by ragnorc** [karelklima/ldkit#54]
Some SPARQL servers like Oxigraph which I am using do not support `application/rdf+json` in CONSTRUCT/DESCRIBE queries. I currently convert `text/turtle` to json manually in a custom fetch function.
What would be the best way ti support this?

**Comment by karelklima** [comment]
For these instances it is possible to use Comunica as the query engine: https://ldkit.io/docs/how-to/query-with-comunica

The reason why LDkit does not support `text/turtle` out of the box is because of performance. In case of JSON response, the browser or JavaScript runner convert the response to JavaScript objects and native types in an efficient way. In comparison with that, parsing of text responses in a format like Turtle is more resource heavy and it is best to be done on server rather then on client.

With that said, it would be beneficial to have `text/turtle` opt-in support out of the box, after all it is probably the most common RDF serialization there is. It is definitely possible to create an alternative lightweight query engine that would support that format as well.

**Comment by arxos-twinu** [comment]
Would love to see more support, including as well application/ld+json. I am currently using stardog and sadly they don't support rdf+json. Any hope on this? 

> Some SPARQL servers like Oxigraph which I am using do not support `application/rdf+json` in CONSTRUCT/DESCRIBE queries. I currently convert `text/turtle` to json manually in a custom fetch function. What would be the best way ti support this?

Any chance you could share your solution? I need to do the same for my case, already had to modify the fetch function to add authentication.

**Comment by karelklima** [comment]
@ragnorc @arxos-twinu I've added support for `text/turtle` to the default query engine so most SPARQL endpoints should now work ouf of the box. Available in version `1.1.0`.

If there are some other formats that would be convenient to include then please let me know and I will add them.
